### ISSUE TITLE
Adicionar Participante na Via Escalada

### ISSUE THREAD

**Issue by rafael-ventura** [rafael-ventura/cume-brasil#100]
### **Objetivo**

> Adicionar o campo de participante na via de escalada.

### **Definições**

> A cada registro, o usuário deve poder adicionar um ou mais participantes daquela escalada.
> Um participante pode ser do tipo, 1* de cordada(Guia), 2* de cordada(Participante) e Misto (ambos); tipo é obrigatório
> O participante além do tipo, também tem as propriedades nome(obrigatório) e email(pode ser nulo)  
## Wireframe (Modelo a seguir por enquanto)
> Ao registrar, o usuário pode adicionar o nome de um participante [A TAREFA #102 ficara responsável por linkar]

### **Passos:**

>

- [ ]
- [ ] 
- [ ]

**Comment by luizfcneto** [comment]
Solução da atividade está no PR: https://github.com/rafael-ventura/cume-brasil/pull/107
Aguardando aprovação
