### ISSUE TITLE
Implementação da Listagem de Vias

### ISSUE THREAD

**Issue by rafael-ventura** [rafael-ventura/cume-brasil#8]
### Implementação da Listagem de Vias

**Objetivo:**  
Desenvolver uma tela que liste todas as vias de escalada, permitindo que os usuários visualizem as informações básicas e naveguem para detalhes, se desejarem.

**Passos:**  
1. **Configuração da Tela de Listagem**:
   - [ ] Criar uma tela dedicada à listagem de vias.
   - [ ] Implementar uma ListView ou equivalente para exibir os cards das vias.
   - [ ] Cada card deve conter informações básicas, como nome da via, grau e montanha.
2. **Integração com o Backend**:
   - [ ] Conectar a tela de listagem ao backend para recuperar a lista de vias.
   - [ ] Implementar funções para buscar dados do backend e preencher a lista.
3. **Navegação**:
   - [ ] Ao clicar em um card, o usuário deve ser redirecionado para a tela de detalhes da via selecionada.

---

**Comment by vitorindio** [comment]
#15 , do a review pls @rafael-ventura
